# Generated by Django 5.1 on 2024-08-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamezone', '0004_remove_personaje_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaje',
            name='nivel',
        ),
        migrations.AddField(
            model_name='personaje',
            name='descripcion',
            field=models.TextField(default='Descripción no proporcionada'),
        ),
    ]
